#!/bin/bash

BACKTITLE="sysconf 0.2.0"
TITLE="Xorg Configuration"

TMP=/tmp/xorgconf.$$
mkdir -p $TMP

handle_exit() {
  if [ "$DEBUG" = "yes" ]
  then
    echo "Debuging information."
    echo "Function  : $1"
    echo "Action    : $2"
    echo "Line      : $3"
    echo "Retval    : $4"
  fi
  rm -rf $TMP
  exit $4
}

main_help() {
  echo a
}

save_configuration() {
  mv $TMP/xorg.conf /etc/X11/xorg.conf.generated
  echo
  echo "Your Xorg server has been configured. Please runt X.."
  echo
}

write_configuration() {
  local REMAININGSTEPS=""
  for FILE in screen mouse monitor card keyboard
  do
    if [ ! -e $TMP/${FILE}_configuration ]
    then
      REMAININGSTEPS="$REMAININGSTEPS $FILE"
    fi
  done
  
  if [ -n "$REMAININGSTEPS" ]
  then
    dialog --backtitle "$BACKTITLE" \
           --title " Error " \
	   --msgbox \
"\n You need to go through all steps to create a
full xorg configuration file.\n
Remaining steps: $REMAININGSTEPS" 0 0
    if [ $? -eq 0 ]
    then
      main
    else
      handle_exit "write_configuration()" "ESC pressed." "$LINENO" "1"
    fi
  fi    
  
  cat << EOF > $TMP/xorg.conf
#
# /etc/X11/xorg.conf - main Xorg configuation file (generated with xorgconf).
#
# For more information on editing this file see xorg.conf (5).
#

Section "ServerLayout"
  Identifier     "X.org Configured"
  Screen         "Screen0
  InputDevice    "Mouse0" "CorePointer"
  InputDevice    "Keyboard0" "CoreKeyboard"
EndSection

Section "Files"
  RgbPath      "/usr/X11R6/lib/X11/rgb"
  ModulePath   "/usr/X11R6/lib/modules"
  FontPath     "/usr/X11R6/lib/X11/fonts/misc/"
  FontPath     "/usr/X11R6/lib/X11/fonts/TTF/"
  FontPath     "/usr/X11R6/lib/X11/fonts/Type1/"
  FontPath     "/usr/X11R6/lib/X11/fonts/75dpi/"
  FontPath     "/usr/X11R6/lib/X11/fonts/100dpi/"
EndSection

Section "Module"
  Load  "dbe"
  Load  "dri"
  Load  "extmod"
  Load  "glx"
  Load  "record"
  Load  "xtrap"
  Load  "freetype"
  Load  "type1"
EndSection

`cat $TMP/keyboard_configuration`

`cat $TMP/mouse_configuration`							

`cat $TMP/monitor_configuration`

`cat $TMP/card_configuration`

`cat $TMP/screen_configuration`

EOF
  dialog --backtitle "$BACKTITLE" \
         --title " $TITLE " \
	 --cancel-label "Exit" \
	 --ok-label "Save" \
	 --extra-button \
	 --extra-label "Back" \
	 --msgbox "`cat $TMP/xorg.conf`" 0 0
  local RETVAL=$?
  case "$RETVAL" in
    0) save_configuration ;;
    1) handle_exit "write_configuration()" "Exit pressed." "$LINENO" "1" ;;
    3) main ;;
   -1) handle_exit "write_configuration()" "ESC pressed." "$LINENO" "1" ;;
  esac
}

main_menu() {
  dialog --backtitle "$BACKTITLE" \
         --title " $TITLE " \
	 --cancel-label "Exit" \
	 --ok-label "Configure" \
	 --help-button \
	 --menu \
"\nPlease select what you would like to configure." 0 0 0 \
"mouse" "Select your mouse type and device." \
"keyboard" "Set your your keyboard type and language set." \
"card" "Select your graphics card and options." \
"monitor" "Configure your monitor." \
"screen" "Set your resolution and modes." \
"write" "Write configuration file." 2> $TMP/main
  local RETVAL=$?
  local SELECTION=`cat $TMP/main`
  case "$RETVAL" in
    0)
      case "$SELECTION" in
        mouse)
	  source modules/mouse
	  configure_mouse
	  unset -f write_mouse_configuration get_mouse_protocol activate_wheel \
	    enable_three_buttons_emulation configure_mouse
	  ;;
	keyboard)
	  source modules/keyboard
	  configure_keyboard
	  unset -f write_keyboard_configuration select_xkb_layout configure_keyboard
	  ;;
	card)
	  source modules/card
	  configure_card
	  unset -f write_card_configuration get_memory_from_user get_card_memory \
	    select_card configure_card
	  ;;
	monitor)
	  source modules/monitor
	  configure_monitor
	  unset -f write_monitor_configuration get_userdefined_monitor_sync get_monitor_vsync \
	    configure_monitor
	  ;;
	screen)
	  source modules/screen
	  configure_screen
	  unset -f write_screen_configuration write_resolution_function configure_screen
	  ;;
	write)
	  write_configuration
      esac
      ;;
    1) handle_exit "main()" "Exit pressed." "$LINENO" "1" ;;
    2) show_main_help ;;
   -1) handle_exit "main()" "ESC pressed." "$LINENO" "1" ;;
  esac
  
  handle_exit "main()" "Final exit." "$LINENO" "0"
}

main_menu
mv -f /etc/X11/xorg.conf /etc/X11/xorg.conf.backup
mv -f /etc/X11/xorg.conf.generated /etc/X11/xorg.conf
