#!/bin/bash

pkg_group() {
  local INDEX=0
   
  for LINE in $(grep -H ^GROUP=$1$ ${PKG_ROOT}${DATABASEDIR}/db/* 2>/dev/null)
  do
    LINE=$(echo $LINE | cut -f 1 -d ':')
    LINE=${LINE##*/}
    echo "$1 $LINE"
    INDEX=$(($INDEX + 1))
  done     

  if [ $INDEX -eq 0 ]
  then
    echo "could not find any packages from group $1."
  fi
}
