#!/bin/bash
#
# /etc/rc.d/checkfs - check all non root filesystems (not network filesystems)
#

. /etc/rc.d/functions

case "$1" in
  start)
    [ -f /fastboot ] && exit 0
    
    MESSAGE=""
    OPTIONS=""
    
    [ "$INITMODE" = "simple" ] && OPTIONS="-C"
    [ -f /forcefsck ] && {
      MESSAGE="(forced)"
      OPTIONS="$OPTIONS -f"
    }
    
    msg "Mounting the root filesystem read-only"
    run mount -n -o remount,ro /
    if [ $? -ne 0 ]
    then
      failure
      echo
      echo "Could not mount the root filesystem in read-only mode."
      echo
      echo "When you press ENTER the system will be halted."
      echo
      echo "Press ENTER to continue."
      echo
      read junk
      umount -a 2>/dev/null
      halt -f
    fi
									
    msg "Checking the root filesystem ${MESSAGE}"
    run fsck $OPTIONS -a -T
    if [ $? -gt 1 ] && [ $? -lt 3 ]
    then
      echo "Filesystems errors were found and fixed."
      echo
      echo "System will be rebooted in 2 seconds."
      sleep 2
      echo "Rebooting..."
      umount -a 2>/dev/null
      mount -n -o remount,ro / 2>/dev/null
      reboot -f
    elif [ $? -gt 3 ]
    then
      echo "Filesystems errors were found and could not be"
      echo "fixed. Please repair manually."
      echo
      echo "CTRL+D will exit the shell and reboot the system."
      echo
      sulogin -p
      echo "Rebooting..."
      umount -a 2>/dev/null
      mount -n -o remount,ro / 2>/dev/null
      reboot -f
    fi
    ;;
  *)
    echo "usage: $0 {start}"
    exit 1
    ;;
esac
