#!/bin/bash
#
# /etc/rc.d/cleanfs - clean the filesystem (/tmp,/var/run and /var/lock)
#

. /etc/rc.d/functions

case "$1" in
  start)
    msg "Removing files from /var/run"
    run find /var/run ! -type d -exec rm -f -- {} \;
    
    > /var/run/utmp
    if grep -q ^utmp /etc/group
    then
      chmod 644 /var/run/utmp
      chgrp utmp /var/run/utmp
    fi
    
    msg "Removing file from /var/lock"
    run find /var/lock ! -type d -exec rm -f -- {} \;
    
    msg "Removing files from /tmp"
    run find /tmp -xdev -mindepth 1 -depth ! -path '/tmp/lost+found*' \
        -exec rm -rf {} \;
	
    mkdir -p /tmp/{.X11-unix,.ICE-unix}
    chmod 1777 /tmp /tmp/{.X11-unix,.ICE-unix}
    chmod 1777 /var/spool/mail 2>/dev/null
    ;;
  *)
    echo "usage: $0 {start}"
    exit 1
    ;;
esac
