#!/bin/bash
#
# /etc/rc.d/ldconfig - configure dynamic linker run time bindings
#

. /etc/rc.d/functions

case "$1" in
  start)
    msg "Configuration dynamic linker run time bindings"
    run /sbin/ldconfig
    ;;
  stop)
    msg "Configuring dynamic linker run time bindings"
    run /sbin/ldconfig
    ;;
  *)
    echo "usage: $0 {start|stop}"
    exit 1
    ;;
esac
