#!/bin/bash
#
# /etc/rc.d/mountroot - mount the root filesystem in read-write mode
#

. /etc/rc.d/functions

case "$1" in
  start)
    msg "Mounting the root filesystem"
    run mount -n -o remount,rw /
    
    # Clear /etc/mtab and possible stale locks.
    > /etc/mtab
    rm -f /etc/mtab~ /etc/mtab~~

    # Write /, /proc and /sys to /etc/mtab.
    mount -f /
    mount -f /proc
    mount -f /sys >/dev/null 2>&1
    ;;
  stop)
    msg "Unmounting the root filesystem"
    run mount -n -o remount,ro /
    ;;
  *)
    echo "usage: $0 {start|stop}"
    exit 1
    ;;
esac
