#!/bin/bash

is_configured() {
  if declare -f $1 >/dev/null 2>&1
  then
    return 0
  else
    return 1
  fi
}

is_running() {
 if ifconfig | grep -q ^$1 >/dev/null 2>&1
 then
   return 0
 else
   return 1
 fi
}
