#!/bin/bash
#
# /sbin/pkg_install - install Decebal Linux compatible packages. (renamed pkg_add)
#
# Copyright (C) 2003-2005 Teodor Adrian Florin <slider@decebal.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

BASEDIR=$(pwd)

if [ ! "$UID" = "0" ]
then
  echo "You need root privilegies to install packages."
  exit 1
fi

FUNCTIONSDIR="/usr/share"
CONFDIR="/etc/dpack"

source $CONFDIR/common
source $FUNCTIONSDIR/dpack/tmp
source $FUNCTIONSDIR/dpack/exit
source $FUNCTIONSDIR/dpack/pkg
source $FUNCTIONSDIR/dpack/depend
source $FUNCTIONSDIR/dpack/msg
source $FUNCTIONSDIR/dpack/exec
source $FUNCTIONSDIR/dpack/log

usage() {
  cat << EOF
usage: pkg_install [options] <package1> <package2> ...
options:
  -d, --nodeps        - skip all dependencies checks
  -f, --force         - force package installation (overwrite existing files)
  -p, --pretend       - only show actions (dont execute them)
  -r, --root <dir>    - use an alternate installation path <dir>
  -v, --verbose       - be more verbose
  -V, --version       - print name, version and license
  -h, --help          - print this message and exit
EOF
}

version() {
  cat << EOF
pkg_install v0.0.2 (dpack v0.1.6)

Copyright (C) 2003-2005 Teodor Adrian Florin <slider@decebal.org>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
EOF
}

PKG_NODEPS=0
PKG_FORCE=0
PKG_PRETEND=0
PKG_VERBOSE=0

PKG_ROOT=""
PKG_ARGS=""

if [ $# -eq 0 ]
then
  echo "error: pkg_install needs an argument." >&2
  usage >&2
  pkg_exit "main()" "check_if_we_have_arguments" "$LINENO" 1
fi

while [ $# -ne 0 ]
do
  case "$1" in
    --nodeps)  PKG_NODEPS=1 ;;
    --force)   PKG_FORCE=1  ;;
    --pretend) PKG_PRETEND=1 ;;
    --verbose) PKG_VERBOSE=1 ;;
    --root)
      PKG_ROOT="$2"
      shift 1
      ;;
    --version)
      version
      exit 0
      ;;
    --help)
      usage
      exit 0
      ;;
    --*)
      echo "error: unrecongnized option." >&2
      usage >&2
      pkg_exit "main()" "unrecognized option (--*)" "$LINENO" 1
      ;;
    -*)
      while getopts "dfpvVhr:-" OPT
      do
        case "$OPT" in
	  d) PKG_NODEPS=1  ;;
	  f) PKG_FORCE=1   ;;
	  p) PKG_PRENETD=1 ;;
          v) PKG_VERBOSE=1 ;;
	  V)
	    version
	    exit 0
	    ;;
	  h)
	    usage
	    exit 0
	    ;;
	  r)
	    PKG_ROOT="$OPTARG"
	    shift 1
	    ;;
	  -)
	    OPTBIND=0
	    break
	    ;;
	  *)
	    usage >&2
            pkg_exit "main()" "unrecognized option (--*)" "$LINENO" 1
	    ;;
        esac
      done
      ;;
    *)
      PKG_ARGS="$1"
      shift 1
      for ARG in 1 2 3 4 5 6 7 8 9 10
      do
        PKG_ARGS="$PKG_ARGS $1"
	shift 1
      done
      ;;
  esac
  shift 1
done

if [ "$PKG_ARGS" = "" ]
then
  echo "error: pkg_install needs an argument <package>" >&2
  usage >&2
  pkg_exit "main()" "no <package> argument" "$LINENO" 1
fi


pkg_install() {
  local PACKAGE="$1"
  local PROTOCOL=$(echo $1 | sed 's|://.*||')
  
  # create our directories if not there
  if [ ! -d /var/lib/pkg/db ]
  then
    mkdir -p /var/lib/pkg/{db,update,virtual,security}
  fi
  
  if [ ! -d /var/log/dpack ]
  then
    mkdir -p /var/log/dpack
  fi
      
  ACTION="install"
  
  source $FUNCTIONSDIR/dpack/shared
  
  if [ "$PROTOCOL" = "http" -o "$PROTOCOL" = "ftp" ]
  then
    msg_start "downloading $(stripurl $PACKAGE)..."
    pkg_download $PACKAGE
    if [ $? -eq 0 ]
    then
      msg_ok
    else
      msg_failed
      msg_error "could not download package."
      pkg_exit "pkg_install()" "downloading $PACKAGE" "$LINENO" 1
    fi
  fi
  
  pkg_check_syntax $PACKAGE
  
  local PKG=$(basename $PACKAGE .tbz2)
  local DIR=$(dirname $PACKAGE)
  local PKGNAME=$(pkgname $PKG)
  
  if pkg_is_installed $PKGNAME
  then
    echo "package '$PKGNAME' already installed (use pkg_upgrade)."
    pkg_exit "pkg_install()" "package $PKGNAME already installed" "$LINENO" 2
  fi
  
  msg_start_nnl "installing $PKGNAME..."
  
  pkg_check_tbz2 $DIR/$PKG
  pkg_check_regular $PACKAGE
  pkg_check_integrity $PACKAGE
  pkg_create_tmp
  pkg_extract_info $PACKAGE
  pkg_check_depends
  pkg_check_conflicts
  pkg_check_files
  pkg_unpack $PACKAGE
  pkg_create_db
  pkg_remove_tmp
  pkg_log "installed ${PACKAGE##*/}"
  msg_ok 
}

for ARG in $PKG_ARGS
do
  pkg_install $ARG
done

cd $BASEDIR

exit 0
